### ISSUE TITLE
[suggestion] move changelog to separate file

### ISSUE THREAD

**Issue by leela52452** [Vel-San/Getoffyourphone#40]
i noticed changelog is part of README.
can you please commit or create it as Changelog.txt or Changelog.md or Changelog.rst.

**Comment by Alikaraki95** [comment]
I might change that, nice suggestion. Thanks mate ^_^

**Comment by Vel-San** [comment]
Done 5c4dbb7ac27886cd7d1015367f753e6cfe488e39 - Thanks.
