### ISSUE TITLE
Doesnt work on xiaomi device (Android 9)

### ISSUE THREAD

**Issue by hungvu193** [Vel-San/Getoffyourphone#42]
It works on my pixel XL (Android 9) but doent work on my xiaomi phone (Android 9), after I choose options and press "LOCK SELECTED APPS!", It just show popup "Select at least 1 app" and no popup of list app was showed to selected app.

**Comment by Vel-San** [comment]
Hey there. Sorry about that but the project has been almost discontinued from my side.. I have no time at the moment to develope/Fix anything in it.

Have you tried a fresh install and not missing any permissions?

Thanks for trying the app.

**Comment by hungvu193** [comment]
@Vel-San Thanks for you reply, I will test again and show you my logcat.
